-- Create guide_versions table
CREATE TABLE IF NOT EXISTS guide_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guide_id BIGINT REFERENCES guides(id) ON DELETE CASCADE,
    title TEXT,
    content TEXT, -- Markdown content
    html_content TEXT, -- HTML content
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add index for faster lookups
CREATE INDEX IF NOT EXISTS idx_guide_versions_guide_id ON guide_versions(guide_id);

-- Enable RLS
ALTER TABLE guide_versions ENABLE ROW LEVEL SECURITY;

-- Allow read access to everyone
CREATE POLICY "Public profiles are viewable by everyone." ON guide_versions
    FOR SELECT USING (true);

-- Allow insert access to authenticated users (or maybe just the author? For now, auth users is fine as the logic is backend/api controlled,
-- but ideally should match guide owner. Since we don't have update policy on versions, insert is enough)
CREATE POLICY "Users can insert versions for their guides" ON guide_versions
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');
